'use client';

import { createContext, useContext, useState } from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import { ThemeContext } from '@/providers/Contexts';
import Navbar from '@/components/Navbar';
import LandingPage from '@/components/LandingPage';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	const [isDark, setIsDark] = useState(true);
	const [isLogged, setIsLogged] = useState(false);

	return (
		<html lang='en'>
			<ThemeContext.Provider value={isDark}>
				<body className={`${isDark ? 'dark bg-black text-white' : ''} ${inter.className}`}>
					<Navbar setIsDark={setIsDark} setIsLogged={setIsLogged} />
					{isLogged ? children : <LandingPage />}
				</body>
			</ThemeContext.Provider>
		</html>
	);
}
